### ISSUE TITLE
Audio stream or azureearmodule

### ISSUE THREAD

**Issue by stefan-balke** [microsoft/azure-percept-advanced-development#10]
Hi,

great news with this development sdk.
However, I was wondering where you document the custom possibilities with the audio module.
Would be interested to get access to the audio stream.
Do you plan to have a similar module as with azureeymodule?

Thanks

**Comment by MaxStrange** [comment]
This is a good question. Let me check with the speech team and get back to you.

**Comment by MaxStrange** [comment]
It sounds like there is a plan in place for something similar, and it should be rolled out sometime in the next few months.

**Comment by stefan-balke** [comment]
Thanks for checking with the team. Looking forward to it!
