### ISSUE TITLE
[Need Help] myriad_compile step is failing in my environemt

### ISSUE THREAD

**Issue by aurotripathy** [microsoft/azure-percept-advanced-development#39]
**Describe the bug**
Not sure if its a bug, my environment is not the same.
Repeated error message below when doing the myriad_compile step
`E: [xLinkUsb] [    367214] [myriad_compile] usb_find_device_with_bcd:266	Library has not been initialized when loaded`

**To Reproduce**
Run up to Step **9** of https://github.com/microsoft/azure-percept-advanced-development/blob/main/machine-learning-notebooks/train-from-scratch/SemanticSegmentationUNet.ipynb
I'm doing the steps **locally** (not on a  Azure ML remote compute instance). I have the model built locally.
Next, I was taking the model thru the conversion steps in the openvino container. 
Container is openvino/ubuntu18_dev:2021.3
Prior steps, listed below, succeeded:
- pytorch model to onnx - OK
- onnx to IR - OK
- IR to blob - Fail

The exact command is 
```
source /opt/intel/openvino_2021/bin/setupvars.sh 

/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/myriad_compile \                                                                                                                    
8    -m intel/bananas.xml -o intel/bananas.blob -VPU_NUMBER_OF_SHAVES 8 -VPU_NUMBER_OF_CMX_SLICES 8 -ip U8 -op FP32 
```
Thank you for taking a look.

**Update**: seems harmless as it generated  a blob file.

**Comment by MaxStrange** [comment]
Hi aurotripathy! Yes, I've noticed the myriad_compile tool complains a lot, but it always seems to produce the blob file. I'll check around and see if we have an issue open with Intel about this, and if not, I'll open one. It's an alarming number of error messages for something that seems to work properly.

**Comment by aurotripathy** [comment]
Thanks for checking with the openvino team (you can get their attentions :-). 
As long as it's harmless, I'll close this.

**Comment by aurotripathy** [comment]
seems harmless
