### ISSUE TITLE
Provide the WebStreamModule code

### ISSUE THREAD

**Issue by dthk-cogmatix** [microsoft/azure-percept-advanced-development#61]
It would be nice if you could provide the WebStreamModule sample code.

**Comment by MaxStrange** [comment]
Yeah, I think the original plan was to open source it, but I am not sure what's going on with it these days. Let me check.

**Comment by MaxStrange** [comment]
Okay, I guess we haven't reached an internal decision on whether that code is going to be open sourced yet. Sorry :(
